//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSphereApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoSphereEntities : DbContext
    {
        private static AutoSphereEntities _context;
        public AutoSphereEntities()
            : base("name=AutoSphereEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static AutoSphereEntities GetContext()
        {
            if(_context== null)
                _context = new AutoSphereEntities();
            return _context;
        }
    
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Countrys> Countrys { get; set; }
        public virtual DbSet<Drives> Drives { get; set; }
        public virtual DbSet<EnterHistory> EnterHistory { get; set; }
        public virtual DbSet<Marks> Marks { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<QR_Codes> QR_Codes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Zones> Zones { get; set; }
        public static Users currentuser = null;
    }
}
