//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSphereApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QR_Codes
    {
        public int CodeID { get; set; }
        public string Code { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
