//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSphereApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestDrive
    {
        public int TestDriveID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Price { get; set; }
        public string Data { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<int> Serv { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
